version: '3'

volumes:
  dadsdatabase:

services:
  postgresql:
    image: "postgres"
    container_name: "my_postgres"
    environment:
    - POSTGRES_USER=<create one here>
    - POSTGRES_PASSWORD=jsturtz
    - POSTGRES_DB=1234
    # Maps port 5432 on host (localhost) to 5432 on container
    ports:
    - "5432:5432"
    volumes:
    - dadsdatabase:/var/lib/postgresql
